name: SSH deploy on push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Add IP to whitelist
        id: addip
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.ADM_TOOLS_API_TOKEN }}" --request POST --data '{"account_id": "${{ secrets.ADM_TOOLS_ACCOUNT_ID }}", "ip": "${{ steps.ip.outputs.ipv4 }}"}' https://adm.tools/action/hosting/account/ssh/ip/send/
      - uses: actions/checkout@v2
      - run: |
          npm i -g npm@8.5.5
          rm -rf package-lock.json node_modules
          npm i
          npm ci
      - run: npm run build
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr build/ --exclude='/src' --exclude='/src' --exclude='/public' --exclude='/node_modules' --exclude='/.idea' --exclude='/.github' --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}
      - name: Remove IP from whitelist
        id: removeip
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.ADM_TOOLS_API_TOKEN }}" --request POST --data '{"account_id": "${{ secrets.ADM_TOOLS_ACCOUNT_ID }}", "ip": "${{ steps.ip.outputs.ipv4 }}"}' https://adm.tools/action/hosting/account/ssh/ip/delete_by_ip/